apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: echo-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
      paths:
        - path: /
          backend:
            serviceName: http-echo-service
            servicePort: 5678
