# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python
image: docker

stages:
  - build
  - deploy

services:
  - docker:dind

cache:
  paths:
    - ~/.cache/pip/

before_script:
  - apk add curl
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - wget "https://get.helm.sh/${HELM_URL}"
  - tar -zxvf "${HELM_URL}"
  - cp ./linux-amd64/helm /usr/bin
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - mv ./kubectl /usr/local/bin/kubectl

variables:
  REGISTRY_URL: "$CI_REGISTRY/ishankhare07"
  HELM_URL: "helm-v3.2.1-linux-amd64.tar.gz"

build_and_push_to_registry:
  stage: build
  only:
    - tags
    #- define-ci-cd
  script:
    - echo "registry url ${CI_REGISTRY}"
    - docker build -f ./code/Dockerfile ./code -t "${REGISTRY_URL}/ahins:${CI_COMMIT_TAG}.prod"
    - docker push "${REGISTRY_URL}/ahins:${CI_COMMIT_TAG}.prod"
    - helm template render --dry-run --debug ./helm_chart --set dockerImage=${REGISTRY_URL}/ahins:${CI_COMMIT_TAG}.prod

create_deploy_in_k8s:
  stage: deploy
  environment:
    name: deploy
  only:
    - tags
  #when: manual
  script:
    - helm template ./helm_chart --set dockerImage=${REGISTRY_URL}/ahins:${CI_COMMIT_TAG}.prod | kubectl apply -f -
    - kubectl get deploy
