image: golang

before_script:
    - cp /builds/ishankhare07/ /go/src/ishankhare07

test:
    stage: test
    script:
        - cd /go/src/ishankhare07/monkey-lang
        - go test ./lexer
        - go test ./token
