sudo: required

language: python
python:
  - "3.6"

services:
  - docker

before_install:
  - docker-compose -p ishankhare07/django-postgres-docker-cluster build
  - chmod +x test.sh

script:
  - ./test.sh
