version: '3.1'
services:
    nginx-dev:
        image: nginx:1.13.7
        container_name: ahins-nginx-dev
        ports:
            - 80:80
        volumes:
            - ./code/mysite/static:/resources/static
            - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - django-dev
        networks:
            ahins:
                aliases:
                    - nginxdev
    nginx-prod:
        image: nginx:1.13.7
        container_name: ahins-nginx-prod
        ports:
            - 80:80
        volumes:
            - ./code/mysite/static:/resources/static
            - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - django
        networks:
            ahins:
                aliases:
                    - nginxprod
    db:
        image: postgres:10.1
        container_name: ahins-pg
        environment:
            - POSTGRES_PASSWORD=example
        ports:
            - 5432:5432
        volumes:
            - ./db/config:/etc/postgresql
            - ./db/log:/var/log/postgresql
            - ./db/databases:/var/lib/postgresql
        networks:
            ahins:
                aliases:
                    - postgres
    django:
        build:
            context: ./code
            dockerfile: Dockerfile
        image: registry.gitlab.com/ishankhare07/ahins:v0.0.2.prod
        container_name: ahins-prod
        working_dir: /code/mysite
        environment:
            - IS_CONTAINER=True
        #command: python mysite/manage.py runserver 0.0.0.0:80
        #on production env
        command: gunicorn -c gunicorn_config.py mysite.wsgi:application
        depends_on:
            - db
        volumes:
            - ./code:/code
        networks:
            ahins:
                aliases:
                    - djangoprod
        # ports:
        #    - 80:80
    django-dev:
        build:
            context: ./code
            dockerfile: Dockerfile
        image: registry.gitlab.com/ishankhare07/ahins:v0.0.2.dev
        container_name: ahins-dev
        working_dir: /code/mysite
        environment:
            - IS_CONTAINER=True
            - IS_DEV_ENV=True
        #command: gunicorn -c gunicorn_config.py mysite.wsgi:application
        command: python manage.py runserver 0.0.0.0:80
        depends_on:
            - db
        volumes:
            - ./code:/code
        networks:
            ahins:
                aliases:
                    - djangodev
        #ports:
        #    - 80:80


networks:
    ahins:
