version: '3.1'
services:
    nginx-dev:
        image: nginx:1.13.7
        container_name: ahins-nginx-dev
        ports:
            - 80:80
        volumes:
            - ./code/mysite/static:/resources/static
            - ./media:/resources/media
            - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - django-dev
        networks:
            ahins:
                aliases:
                    - nginxdev
    nginx-prod:
        build:
          context: ./nginx
          dockerfile: Dockerfile
        image: registry.gitlab.com/ishankhare07/ahins/nginx:v0.0.2.prod
        # image: nginx:1.13.7
        container_name: ahins-nginx-prod
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./code/mysite/static:/resources/static
            - ~/media:/resources/media
            - /etc/letsencrypt/archive/ishankhare.com:/certs
        depends_on:
            - django
        networks:
            ahins:
                aliases:
                    - nginxprod
    db:
        image: postgres:10.1
        container_name: ahins-pg
        environment:
            - POSTGRES_PASSWORD=example
            - POSTGRES_USER=ahins
            - POSTGRES_DB=ahins
        ports:
            - 5432:5432
        volumes:
            - ./db/config:/etc/postgresql
            - ./db/log:/var/log/postgresql
            - ./db/databases:/var/lib/postgresql
        networks:
            ahins:
                aliases:
                    - postgres
    django:
        build:
            context: ./code
            dockerfile: Dockerfile
        image: registry.gitlab.com/ishankhare07/ahins:v0.0.8.prod
        container_name: ahins-prod
        working_dir: /code/mysite
        environment:
            - IS_CONTAINER=True
        command: gunicorn -c gunicorn_config.py mysite.wsgi:application
        volumes:
            - ./code:/code
            - ~/media:/code/mysite/media
        networks:
            ahins:
                aliases:
                    - djangoprod
    django-dev:
        build:
            context: ./code
            dockerfile: Dockerfile
        image: registry.gitlab.com/ishankhare07/ahins:v0.0.6.dev
        container_name: ahins-dev
        working_dir: /code/mysite
        environment:
            - IS_CONTAINER=True
            - IS_DEV_ENV=True
        command: python manage.py runserver 0.0.0.0:80
        depends_on:
            - db
        volumes:
            - ./code:/code
            - ./media:/code/mysite/media
        networks:
            ahins:
                aliases:
                    - djangodev

networks:
    ahins:
