FROM nginx:1.13.7
COPY ./prod.conf /etc/nginx/conf.d/default.conf
#RUN apt-get update
#RUN apt-get install -y software-properties-common
#RUN add-apt-repository -y ppa:certbot/certbot
#RUN apt-get update
#RUN apt-get install -y certbot 
