apiVersion: apps/v1
kind: Deployment
metadata:
  name: ahins
  labels:
    app: django
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: {{ .Values.dockerImage }}
          command: ["gunicorn -c gunicorn_config.py mysite.wsgi:application"]
          ports:
            - containerPort: 8000
