# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-15 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='background_image',
            field=models.TextField(default='//placehold.it/500x200'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
