# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-11-02 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181024_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogtags',
            options={'verbose_name': 'BlogTag'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Tag'},
        ),
        migrations.RenameField(
            model_name='blogtags',
            old_name='blog_id',
            new_name='blog',
        ),
        migrations.RenameField(
            model_name='blogtags',
            old_name='tag_id',
            new_name='tag',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(to='blog.Tags'),
        ),
    ]
