# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-11-02 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191102_1928'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blogtags',
            unique_together=set([('blog', 'tag')]),
        ),
    ]
