# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-11-02 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191102_2013'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blogtags',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='blogtags',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='blogtags',
            name='tag',
        ),
        migrations.DeleteModel(
            name='BlogTags',
        ),
    ]
